// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.DeadSpace.Virus;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.Virus.UI;

[GenerateTypedNameReferences]
public sealed partial class VirusDiagnoserConsoleWindow : DefaultWindow
{
    private VirusDiagnoserConsoleBoundUserInterfaceState? _lastUpdate;
    public VirusStrainRecord? SelectedStrainRecord => _selectedStrainRecord;
    private VirusStrainRecord? _selectedStrainRecord;

    public VirusDiagnoserConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        MasterTabContainer.SetTabTitle(0, Loc.GetString("virus-diagnoser-tab-server"));
        MasterTabContainer.SetTabTitle(1, Loc.GetString("virus-diagnoser-tab-diagnoser"));
        MasterTabContainer.SetTabTitle(2, Loc.GetString("virus-diagnoser-tab-analyzer"));
    }

    public void Populate(VirusDiagnoserConsoleBoundUserInterfaceState state)
    {
        _lastUpdate = state;
        StartAnalysButton.Disabled = true;
        ScanVirusButton.Disabled = true;
        CheckBloodVirusButton.Disabled = true;

        SummaryLabel.Text = Loc.GetString("virus-diagnoser-summary",
            ("strains", state.Strains.Count),
            ("points", state.Points));

        var amountMsg = new FormattedMessage();
        amountMsg.AddMarkupOrThrow(Loc.GetString("research-console-menu-research-points-text",
            ("points", state.Points)));
        ResearchAmountLabel.SetMessage(amountMsg);

        // Состояние 1: анализатор веществ недоступен
        if (!state.SolutionAnalyzerConnected)
        {
            SolutionAnalyzerMissing.Visible = true;
            SolutionAnalyzerFar.Visible = false;
            SolutionAnalyzerContents.Visible = false;
        }
        // Состояние 2: анализатор веществ далеко
        else if (!state.SolutionAnalyzerInRange)
        {
            SolutionAnalyzerMissing.Visible = false;
            SolutionAnalyzerFar.Visible = true;
            SolutionAnalyzerContents.Visible = false;
        }
        // Состояние 3: анализатор веществ доступен
        else
        {
            SolutionAnalyzerMissing.Visible = false;
            SolutionAnalyzerFar.Visible = false;
            SolutionAnalyzerContents.Visible = true;
            SetSolutionAnalyzerStatus(
                state.SolutionAnalyzerStatus,
                state.SolutionAnalyzerHasSample,
                state.SolutionAnalyzerScanProgress);
            StartAnalysButton.Disabled =
                state.SolutionAnalyzerStatus == VirusSolutionAnalyzerStatus.Scanning ||
                !state.SolutionAnalyzerHasSample ||
                !state.DataServerConnected ||
                !state.DataServerInRange;
        }

        // Состояние 1: сервер недоступен
        if (!state.DataServerConnected)
        {
            ServerMissing.Visible = true;
            ServerFar.Visible = false;
            ServerContents.Visible = false;
        }
        // Состояние 2: сервер далеко
        else if (!state.DataServerInRange)
        {
            ServerMissing.Visible = false;
            ServerFar.Visible = true;
            ServerContents.Visible = false;
        }
        // Состояние 3: сервер доступен
        else
        {
            ServerMissing.Visible = false;
            ServerFar.Visible = false;
            ServerContents.Visible = true;
            ServerStatusLabel.Text = Loc.GetString("virus-diagnoser-status-ready");
            ServerStatusLabel.ModulateSelfOverride = Color.FromHex("#3fb950");

            // Обновление списка штаммов
            RebuildStrainRows(state.Strains);

            StrainEmptyLabel.Visible = state.Strains.Count == 0;
            StrainEmptyLabel.Text = Loc.GetString("virus-diagnoser-strain-empty");
            UpdateServerTabButtons();
        }

        if (!state.DiagnoserConnected)
        {
            DiagnoserMissing.Visible = true;
            DiagnoserFar.Visible = false;
            DiagnoserContents.Visible = false;
        }
        else if (!state.DiagnoserInRange)
        {
            DiagnoserMissing.Visible = false;
            DiagnoserFar.Visible = true;
            DiagnoserContents.Visible = false;
        }
        else
        {
            DiagnoserMissing.Visible = false;
            DiagnoserFar.Visible = false;
            DiagnoserContents.Visible = true;
            SetDiagnoserStatus(
                state.DiagnoserStatus,
                state.DiagnoserHasSample || state.DiagnoserHasBloodSample,
                state.DiagnoserScanProgress);
            var diagnoserBusy = IsDiagnoserBusy(state.DiagnoserStatus);
            ScanVirusButton.Disabled =
                diagnoserBusy ||
                !state.DiagnoserHasSample;
            CheckBloodVirusButton.Disabled =
                diagnoserBusy ||
                !state.DiagnoserHasBloodSample;
            UpdateServerTabButtons();
        }
    }

    private void UpdateServerTabButtons()
    {
        var selectedRecord = _selectedStrainRecord;

        var nothingSelected = selectedRecord == null;
        var diagnoserUnavailable = _lastUpdate == null ||
            !_lastUpdate.DiagnoserConnected ||
            !_lastUpdate.DiagnoserInRange;
        var diagnoserBusy = _lastUpdate != null && IsDiagnoserBusy(_lastUpdate.DiagnoserStatus);

        DeleteStrainButton.Disabled = nothingSelected;
        PrintReportButton.Disabled = nothingSelected || diagnoserUnavailable || diagnoserBusy;
        GenerateVirusButton.Disabled = nothingSelected || diagnoserUnavailable || diagnoserBusy;

        if (selectedRecord is { } record)
        {
            SelectedStrainStatusLabel.Text = Loc.GetString("virus-diagnoser-selected-strain",
                ("strain", record.Strain),
                ("time", record.Time));
            SelectedStrainStatusLabel.ModulateSelfOverride = Color.FromHex("#58a6ff");
        }
        else
        {
            SelectedStrainStatusLabel.Text = Loc.GetString("virus-diagnoser-select-strain");
            SelectedStrainStatusLabel.ModulateSelfOverride = Color.LightGray;
        }
    }

    private void RebuildStrainRows(List<VirusStrainRecord> records)
    {
        StrainRows.RemoveAllChildren();

        if (_selectedStrainRecord is { } currentRecord &&
            !records.Contains(currentRecord))
        {
            _selectedStrainRecord = null;
        }

        foreach (var record in records)
        {
            var selected = _selectedStrainRecord is { } selectedRecord && selectedRecord.Equals(record);

            var row = new Button
            {
                ToggleMode = true,
                Pressed = selected,
                HorizontalExpand = true,
                MinHeight = 28,
                ClipText = true,
                ToolTip = Loc.GetString("virus-diagnoser-selected-strain",
                    ("strain", record.Strain),
                    ("time", record.Time))
            };

            var content = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 8,
                HorizontalExpand = true,
                Margin = new Thickness(4, 0, 4, 0)
            };

            content.AddChild(new Label
            {
                Text = record.Strain,
                MinWidth = 260,
                HorizontalExpand = true,
                ClipText = true
            });

            content.AddChild(new Label
            {
                Text = record.Time,
                MinWidth = 170,
                HorizontalAlignment = HAlignment.Right,
                ClipText = true,
                FontColorOverride = Color.LightGray
            });

            row.AddChild(content);
            row.OnPressed += _ =>
            {
                _selectedStrainRecord = record;
                RebuildStrainRows(_lastUpdate?.Strains ?? new List<VirusStrainRecord>());
                UpdateServerTabButtons();
            };

            StrainRows.AddChild(row);
        }
    }

    private void SetDiagnoserStatus(VirusDiagnoserStatus status, bool hasSample, int progress)
    {
        DiagnoserProgressLabel.Visible = false;

        if (status == VirusDiagnoserStatus.On && !hasSample)
        {
            DiagnoserStatusLabel.Text = Loc.GetString("virus-diagnoser-status-no-sample");
            DiagnoserStatusLabel.ModulateSelfOverride = Color.FromHex("#f0883e");
            return;
        }

        var (message, color) = status switch
        {
            VirusDiagnoserStatus.Off => ("virus-diagnoser-status-unavailable", "#f85149"),
            VirusDiagnoserStatus.Printing => ("virus-diagnoser-status-printing", "#f0883e"),
            VirusDiagnoserStatus.Scanning => ("virus-diagnoser-status-scanning", "#f0883e"),
            VirusDiagnoserStatus.BloodScanning => ("virus-diagnoser-status-blood-scanning", "#f0883e"),
            VirusDiagnoserStatus.Denial => ("virus-diagnoser-status-denial", "#f85149"),
            VirusDiagnoserStatus.Successfully => ("virus-diagnoser-status-success", "#3fb950"),
            VirusDiagnoserStatus.GenerateVirus => ("virus-diagnoser-status-generating", "#f0883e"),
            _ => ("virus-diagnoser-status-ready", "#3fb950")
        };

        DiagnoserStatusLabel.Text = Loc.GetString(message);
        DiagnoserStatusLabel.ModulateSelfOverride = Color.FromHex(color);

        if (status is not (VirusDiagnoserStatus.Scanning or VirusDiagnoserStatus.BloodScanning))
            return;

        DiagnoserProgressLabel.Text = Loc.GetString("virus-diagnoser-process-status", ("percent", progress));
        DiagnoserProgressLabel.ModulateSelfOverride = Color.FromHex(color);
        DiagnoserProgressLabel.Visible = true;
    }

    private void SetSolutionAnalyzerStatus(VirusSolutionAnalyzerStatus status, bool hasSample, int progress)
    {
        SolutionAnalyzerProgressLabel.Visible = false;

        if (status == VirusSolutionAnalyzerStatus.On && !hasSample)
        {
            SolutionAnalyzerStatusLabel.Text = Loc.GetString("virus-diagnoser-status-no-sample");
            SolutionAnalyzerStatusLabel.ModulateSelfOverride = Color.FromHex("#f0883e");
            return;
        }

        var (message, color) = status switch
        {
            VirusSolutionAnalyzerStatus.Off => ("virus-diagnoser-status-unavailable", "#f85149"),
            VirusSolutionAnalyzerStatus.Scanning => ("virus-solution-analyser-status-scanning", "#f0883e"),
            VirusSolutionAnalyzerStatus.Denial => ("virus-solution-analyser-status-denial", "#f85149"),
            VirusSolutionAnalyzerStatus.Successfully => ("virus-solution-analyser-status-success", "#3fb950"),
            _ => ("virus-diagnoser-status-ready", "#3fb950")
        };

        SolutionAnalyzerStatusLabel.Text = Loc.GetString(message);
        SolutionAnalyzerStatusLabel.ModulateSelfOverride = Color.FromHex(color);

        if (status != VirusSolutionAnalyzerStatus.Scanning)
            return;

        SolutionAnalyzerProgressLabel.Text = Loc.GetString("virus-diagnoser-process-status", ("percent", progress));
        SolutionAnalyzerProgressLabel.ModulateSelfOverride = Color.FromHex(color);
        SolutionAnalyzerProgressLabel.Visible = true;
    }

    private bool IsDiagnoserBusy(VirusDiagnoserStatus status)
    {
        return status is VirusDiagnoserStatus.Printing
            or VirusDiagnoserStatus.Scanning
            or VirusDiagnoserStatus.BloodScanning
            or VirusDiagnoserStatus.GenerateVirus;
    }

}
