using System;
using Content.Shared.DeadSpace.CodeLock;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client.DeadSpace.CodeLock
{
    [GenerateTypedNameReferences]
    public sealed partial class CodeLockMenu : DefaultWindow
    {
        public event Action<int>? OnKeypadButtonPressed;
        public event Action? OnClearButtonPressed;
        public event Action? OnEnterButtonPressed;

        public CodeLockMenu()
        {
            RobustXamlLoader.Load(this);
            FillKeypadGrid();
        }

        /// <summary>
        ///     Fill keypad buttons in keypad grid
        /// </summary>
        private void FillKeypadGrid()
        {
            // add 3 rows of keypad buttons (1-9)
            for (var i = 1; i <= 9; i++)
            {
                AddKeypadButton(i);
            }

            // clear button
            var clearBtn = new Button()
            {
                Text = "C"
            };
            clearBtn.OnPressed += _ => OnClearButtonPressed?.Invoke();
            KeypadGrid.AddChild(clearBtn);

            // zero button
            AddKeypadButton(0);

            // enter button
            var enterBtn = new Button()
            {
                Text = "E"
            };
            enterBtn.OnPressed += _ => OnEnterButtonPressed?.Invoke();
            KeypadGrid.AddChild(enterBtn);
        }

        private void AddKeypadButton(int i)
        {
            var btn = new Button()
            {
                Text = i.ToString()
            };

            btn.OnPressed += _ => OnKeypadButtonPressed?.Invoke(i);
            KeypadGrid.AddChild(btn);
        }

        public void UpdateState(CodeLockUiState state)
        {
            string firstMsg, secondMsg;

            switch (state.Status)
            {
                case CodeLockStatus.AWAIT_CODE:
                    firstMsg = Loc.GetString("codelock-user-interface-first-status-input-code");
                    secondMsg = Loc.GetString("codelock-user-interface-second-status-current-code",
                        ("code", VisualizeCodeHidden(state.EnteredCodeLength, state.CodeLength)));
                    break;
                case CodeLockStatus.UNLOCKED:
                    firstMsg = Loc.GetString("codelock-user-interface-first-status-device-unlocked");
                    secondMsg = Loc.GetString("codelock-user-interface-second-status-unlocked");
                    break;
                case CodeLockStatus.COOLDOWN:
                    firstMsg = Loc.GetString("codelock-user-interface-first-status-device-cooldown");
                    secondMsg = Loc.GetString("codelock-user-interface-second-status-time",
                        ("time", state.CooldownTime));
                    break;
                case CodeLockStatus.CHANGE:
                    firstMsg = Loc.GetString("codelock-user-interface-first-status-input-new-code");
                    secondMsg = Loc.GetString("codelock-user-interface-second-status-current-code",
                        ("code", VisualizeCode(state.EnteredCodeLength, state.MaxCodeLength, state.EnteredCode)));
                    break;
                default:
                    firstMsg = Loc.GetString("nuke-user-interface-status-error");
                    secondMsg = Loc.GetString("nuke-user-interface-status-error");
                    break;
            }

            FirstStatusLabel.Text = firstMsg;
            SecondStatusLabel.Text = secondMsg;
        }

        private string VisualizeCode(int codeLength, int maxLength, string? enteredCode)
        {
            var safeMaxLength = Math.Max(0, maxLength);
            var code = enteredCode ?? string.Empty;
            if (code.Length > safeMaxLength)
                code = code[..safeMaxLength];

            return code.PadRight(safeMaxLength, '_');
        }

        private string VisualizeCodeHidden(int codeLength, int maxLength)
        {
            var safeMaxLength = Math.Max(0, maxLength);
            var safeCodeLength = Math.Clamp(codeLength, 0, safeMaxLength);
            var code = new string('*', safeCodeLength);
            var blanksCount = safeMaxLength - safeCodeLength;
            var blanks = new string('_', blanksCount);
            return code + blanks;
        }
    }
}
