- type: cargoProduct
  id: SecurityArmor
  icon:
    sprite: Clothing/OuterClothing/Armor/bulletproof.rsi
    state: icon
  product: CrateSecurityArmor
  cost: 15000 # DS14
  category: cargoproduct-category-name-security
  group: security # DS14

- type: cargoProduct
  id: SecurityHelmet
  icon:
    sprite: Clothing/Head/Helmets/security.rsi
    state: icon
  product: CrateSecurityHelmet
  cost: 750 # DS14
  category: cargoproduct-category-name-security
  group: security # DS14

- type: cargoProduct
  id: SecurityNonLethal
  icon:
    sprite: Objects/Weapons/Guns/Battery/disabler.rsi
    state: base
  product: CrateSecurityNonlethal
  cost: 3750 # DS14
  category: cargoproduct-category-name-security
  group: security # DS14

- type: cargoProduct
  id: SecuritySupplies
  icon:
    sprite: Objects/Storage/boxes.rsi
    state: box_security
  product: CrateSecuritySupplies
  cost: 250 # DS14
  category: cargoproduct-category-name-security
  group: security # DS14

- type: cargoProduct
  id: SecurityRestraints
  icon:
    sprite: Objects/Misc/handcuffs.rsi
    state: handcuff
  product: CrateRestraints
  cost: 1000
  category: cargoproduct-category-name-security
  group: security # DS14

- type: cargoProduct
  id: SecurityBiosuit
  icon:
    sprite: Clothing/Head/Hoods/Bio/security.rsi
    state: icon
  product: CrateSecurityBiosuit
  cost: 6000 # DS14
  category: cargoproduct-category-name-security
  group: security # DS14

- type: cargoProduct
  id: SecurityBarrier
  icon:
    sprite: Objects/Specific/Security/barrier.rsi
    state: idle
  product: DeployableBarrier
  cost: 500 #DS14
  category: cargoproduct-category-name-security
  group: security # DS14

- type: cargoProduct
  id: SecurityNonlethalThrowables
  icon:
    sprite: Objects/Weapons/Grenades/stingergrenade.rsi
    state: icon
  product: CrateSecNonlethalThrowables
  cost: 2500
  category: cargoproduct-category-name-security
  group: security # DS14

- type: cargoProduct
  id: SecurityGenPopCloset
  icon:
    sprite: Structures/Storage/closet.rsi
    state: genpop
  product: LockerPrisoner
  cost: 250
  category: cargoproduct-category-name-security
  group: security # DS14

# DS14-start

- type: cargoProduct
  id: SecurityHardsuit
  icon:
    sprite: Clothing/OuterClothing/Hardsuits/security.rsi
    state: icon
  product: CrateSecurityHardsuit
  cost: 5000
  category: cargoproduct-category-name-security
  group: security # DS14

- type: cargoProduct
  id: SecurityUSSPjuggernaut
  icon:
    sprite: _ADT/Clothing/OuterClothing/Armor/usspjuggernaut.rsi
    state: icon
  product: CrateSecurityUSSPjuggernaut
  cost: 10000
  category: cargoproduct-category-name-security
  group: security # DS14

- type: cargoProduct
  id: TrainingBombs
  icon:
    sprite: Structures/Machines/bomb.rsi
    state: training-bomb
  product: CrateTrainingBombs
  cost: 1000
  category: cargoproduct-category-name-security
  group: security # DS14


- type: cargoProduct
  id: JetpackSecurity
  icon:
    sprite: Objects/Tanks/Jetpacks/security.rsi
    state: icon
  product: CrateSecurityJetpack
  cost: 2500
  category: cargoproduct-category-name-security
  group: security # DS14

- type: cargoProduct
  id: PortableFlasher
  icon:
    sprite:  Objects/Weapons/pflash.rsi
    state: on
  product: PortableFlasher
  cost: 1000
  category: cargoproduct-category-name-security
  group: security # DS14

- type: cargoProduct
  id: CrateSecurityGlovesCombat
  icon:
    sprite:  Clothing/Hands/Gloves/combat.rsi
    state: icon
  product: CrateSecurityGlovesCombat
  cost: 2000
  category: cargoproduct-category-name-security
  group: security # DS14

- type: cargoProduct
  id: AtmosphericsLiquidOxygenSec
  icon:
    sprite: Structures/Storage/canister.rsi
    state: blue
  product: LiquidOxygenCanister
  cost: 1000
  category: cargoproduct-category-name-security
  group: security # DS14

- type: cargoProduct
  id: CrateSecurityBootsMagSecurity
  icon:
    sprite:  _DeadSpace/Clothing/Shoes/Boots/sec_mag_boots.rsi
    state: icon
  product: CrateSecurityBootsMagSecurity
  cost: 1000
  category: cargoproduct-category-name-security
  group: security # DS14
