- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
#DS14-soyuz-start time requirement
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 10h
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 10h
    - !type:OverallPlaytimeRequirement
      time: 80h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 40h
#DS14-soyuz-end
  weight: 5
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brigmedic # DS14
  - Brig
  - Armory
  - Maintenance
  - External
  - Detective
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Security
  wage: 80
  #end-backmen: currency
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      # DS14-Start
      - type: Skill
        group: BasicAndShuttleControl
      # DS14-End

- type: startingGear
  id: WardenGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    gloves: ClothingHandsGlovesCombat # DS14-Soyuz
  storage:
    back:
    - Flash
    - HyperLinkBookCorporateLaw
    - HyperLinkBookSOPSecurity
    - ERTloadoutSecuritySecondary # DS14
    - ForensicScanner #DS14-Soyuz

- type: chameleonOutfit
  id: WardenChameleonOutfit
  job: Warden
  hasMindShield: true
  equipment:
    head: ClothingHeadHatWarden
    mask: ClothingMaskGasSecurity
    outerClothing: ClothingOuterCoatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    neck: Dinkystar
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack
