- type: job
  id: CentralCommandBlueShieldOfficer
  name: job-name-blue-shield-officer
  description: job-description-blue-shield-officer
  playTimeTracker: JobCentralCommandBlueShieldOfficer
  setPreference: false
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 252000 # 70 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # 20 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hours
  startingGear: CentcomBlueShieldGear
  icon: "JobIconBlueShieldOfficer"
  supervisors: job-supervisors-centcom-administrator
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant, DeathRattleImplantCentcomm ]
  - !type:AddComponentSpecial
    components:
    - type: AntagImmune
    - type: ZombieImmune
    - type: NpcFactionMember
      factions:
      - CentralCommand

- type: entity
  parent: ClothingBackpackBlueShield
  id: ClothingBackpackBlueShieldCentComFilled
  name: модифицированный рюкзак оперативника КГБ # DS14-Soyuz
  description: Рюкзак оперативника КГБ с функцией РИГ. # DS14-Soyuz
  suffix: Заполненный, ГенШтаб # DS14-Soyuz
  components:
  - type: StorageFill
    contents:
      - id: BoxMRE
      - id: ADTtelescopicBaton
      - id: TelescopicShield
      - id: MagazinePistolSubMachineGun
        amount: 3
      - id: MedkitCombatFilled
        amount: 2 
      - id: HandheldCrewMonitor
      - id: Zipties
        amount: 2
      - id: CelestinMedipen
        amount: 2
      - id: ClothingNeckCapeBlueShield # DS14-Soyuz
      - id: KGBloadoutSecondary # DS14-Soyuz
      - id: KGBloadoutPrimary # DS14-Soyuz

- type: entity
  id: ClothingBeltMilitaryWebbingBlueShieldCentComFilled
  parent: ClothingBeltMilitaryWebbingBlueShieldFilled
  name: РПС оперативника КГБ # DS14-Soyuz
  description: РПС, которую носят оперативники КГБ # DS14-Soyuz
  suffix: Заполненный, ГенШтаб # DS14-Soyuz
  components:
  - type: StorageFill
    contents:
      - id: JawsOfLife
      - id: PowerDrill
      - id: WelderExperimental
      # - id: ADTCombatHypo # DS14-Soyuz disabled
      - id: ChemistryBottleEphedrine
      - id: ChemistryBottleOmnizine
      - id: ChemistryBottleOmnizine
      - id: ChemistryBottleBicaridine
      - id: ChemistryBottleDexalinPlus
      - id: ChemistryBottleDermaline

- type: startingGear
  id: CentcomBlueShieldGear
  equipment:
    head: ClothingHeadHatBeretBlueShield
    jumpsuit: ClothingUniformJumpsuitBlueShield
    # back: ClothingBackpackBlueShieldCentComFilled
    mask: ClothingMaskGasSecurity
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterBlackCoatOKGB # DS14-Soyuz
    shoes: ClothingShoesBootsJackFilled
    id: BlueShieldOfficerPDA
    pocket1: PistolBlueShield
    pocket2: WeaponDisabler
    belt: ClothingBeltMilitaryWebbingBlueShieldCentComFilled
  storage:
    outerClothing:
    - ClothingEyesGlassesMeson
    - DoubleEmergencyOxygenTankFilled
    - PinpointerUniversal


- type: chameleonOutfit
  id: CentralCommandBlueShieldOfficerChameleonOutfit
  job: CentralCommandBlueShieldOfficer
  equipment:
    head: ClothingHeadHatBeretBlueShield
    mask: ClothingMaskGasSecurity
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicBlueShield
    shoes: ClothingShoesBootsJack
    belt: ClothingBeltMilitaryWebbingMed
