// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Globalization;
using System.Text;
using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.EnergySeller;
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Shared.Localization;

namespace Content.Client.DeadSpace.EnergySeller;

[GenerateTypedNameReferences]
public sealed partial class EnergySellerUserInterface : FancyWindow
{
    public event Action<int>? OnConfirmSellLimit;
    public event Action<int>? OnConfirmSpeedCharge;

    private bool _updatingControls;

    public EnergySellerUserInterface()
    {
        RobustXamlLoader.Load(this);

        ChargeSpeedSlider.OnValueChanged += _ => OnSliderChanged(ChargeSpeedSlider, ChargeSpeedValue, ChargeSpeedLineEdit);
        MaxChargeSlider.OnValueChanged += _ => OnSliderChanged(MaxChargeSlider, LimitSellValue, MaxChargeLineEdit);

        ChargeSpeedLineEdit.OnTextChanged += args => OnInputChanged(args.Text, ChargeSpeedSlider, ChargeSpeedValue);
        MaxChargeLineEdit.OnTextChanged += args => OnInputChanged(args.Text, MaxChargeSlider, LimitSellValue);

        ChargeSpeedLineEdit.OnTextEntered += _ => ConfirmSpeedCharge();
        MaxChargeLineEdit.OnTextEntered += _ => ConfirmSellLimit();

        SpeedChargeConfirm.OnPressed += _ => ConfirmSpeedCharge();
        SellLimitConfirm.OnPressed += _ => ConfirmSellLimit();
    }

    public void UpdateState(BoundUserInterfaceState state)
    {
        var castState = (EnergySellerBoundUserInterfaceState)state;

        _updatingControls = true;

        ChargeSpeedSlider.MaxValue = castState.MaxChargeRate;
        ChargeSpeedSlider.SetValueWithoutEvent(castState.NowChargeRate);
        SetValueLabel(ChargeSpeedValue, castState.NowChargeRate);
        SetValueLabel(ChargeSpeedMaxLabel, castState.MaxChargeRate);

        if (!ChargeSpeedLineEdit.HasKeyboardFocus())
            ChargeSpeedLineEdit.Text = FormatInputValue(castState.NowChargeRate);

        MaxChargeSlider.MaxValue = castState.MaxLimit;
        MaxChargeSlider.SetValueWithoutEvent(castState.NowLimit);
        SetValueLabel(MaxChargeMaxLabel, castState.MaxLimit);
        SetValueLabel(LimitSellValue, castState.NowLimit);

        if (!MaxChargeLineEdit.HasKeyboardFocus())
            MaxChargeLineEdit.Text = FormatInputValue(castState.NowLimit);

        _updatingControls = false;
    }

    private void ConfirmSpeedCharge()
    {
        OnConfirmSpeedCharge?.Invoke(GetRequestedValue(ChargeSpeedLineEdit, ChargeSpeedSlider));
    }

    private void ConfirmSellLimit()
    {
        OnConfirmSellLimit?.Invoke(GetRequestedValue(MaxChargeLineEdit, MaxChargeSlider));
    }

    private void OnSliderChanged(Slider slider, Label valueLabel, LineEdit lineEdit)
    {
        if (_updatingControls)
            return;

        var value = GetSliderValue(slider);
        SetValueLabel(valueLabel, value);

        _updatingControls = true;
        lineEdit.Text = FormatInputValue(value);
        _updatingControls = false;
    }

    private void OnInputChanged(string text, Slider slider, Label valueLabel)
    {
        if (_updatingControls || !TryParsePower(text, out var value))
            return;

        value = ClampToSlider(value, slider);
        slider.SetValueWithoutEvent(value);
        SetValueLabel(valueLabel, value);
    }

    private static int GetRequestedValue(LineEdit lineEdit, Slider slider)
    {
        if (TryParsePower(lineEdit.Text, out var value))
            return ClampToSlider(value, slider);

        return GetSliderValue(slider);
    }

    private static int ClampToSlider(int value, Slider slider)
    {
        return Math.Clamp(value, (int) slider.MinValue, (int) slider.MaxValue);
    }

    private static int GetSliderValue(Slider slider)
    {
        return (int) Math.Round(slider.Value, MidpointRounding.AwayFromZero);
    }

    private static void SetValueLabel(Label label, int value)
    {
        label.Text = Loc.GetString("energy-seller-ui-watts", ("value", FormatInputValue(value)));
    }

    private static string FormatInputValue(int value)
    {
        return value.ToString("N0", CultureInfo.InvariantCulture).Replace(",", " ");
    }

    private static bool TryParsePower(string text, out int value)
    {
        value = 0;

        if (string.IsNullOrWhiteSpace(text))
            return false;

        var digits = new StringBuilder(text.Length);

        foreach (var character in text)
        {
            if (char.IsDigit(character))
                digits.Append(character);
        }

        return digits.Length > 0 && int.TryParse(digits.ToString(), NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
    }
}
