// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Linq;
using Content.Client.DeadSpace.ERT;
using Content.Shared.DeadSpace.ERT;
using Content.Shared.DeadSpace.ERT.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Maths;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    public sealed partial class ERTCallWindow : DefaultWindow
    {
        [Dependency] private readonly IEntityManager _entMan = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

        private readonly ErtResponseSystem _ertSystem;

        private int? _selectedPendingRequestId;
        private int? _selectedApprovedRequestId;
        private int? _selectedManualApprovedRequestId;
        private string? _selectedAutoSpawnTeamProtoId;

        public ERTCallWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _ertSystem = _entMan.System<ErtResponseSystem>();

            RequestsTabContainer.SetTabTitle(0, Loc.GetString("ert-admin-pending-tab"));
            RequestsTabContainer.SetTabTitle(1, Loc.GetString("ert-admin-approved-tab"));
            RequestsTabContainer.SetTabTitle(2, Loc.GetString("ert-admin-manual-approved-tab"));

            RefreshButton.OnPressed += _ => Refresh();
            SetCooldownButton.OnPressed += _ => SetCooldown();
            SetPointsButton.OnPressed += _ => SetPoints();

            PendingRequestsList.OnItemSelected += OnPendingRequestSelected;
            RejectPendingButton.OnPressed += _ => RejectPending();
            ApprovePendingManualButton.OnPressed += _ => ApprovePendingManual();
            ApprovePendingAutoButton.OnPressed += _ => ApprovePendingAuto();

            ApprovedRequestsList.OnItemSelected += OnApprovedRequestSelected;
            AutoSpawnTeamList.OnItemSelected += OnAutoSpawnTeamSelected;
            SetArrivalButton.OnPressed += _ => SetArrival();
            SetReasonButton.OnPressed += _ => SetReason();
            ChangeApprovedTeamButton.OnPressed += _ => ChangeApprovedTeam();
            QueueAutoSpawnButton.OnPressed += _ => QueueAutoSpawnRequest();
            CancelApprovedAutoSpawnButton.OnPressed += _ => CancelApprovedRequest();
            MoveApprovedToManualButton.OnPressed += _ => MoveApprovedToManual();

            ManualApprovedRequestsList.OnItemSelected += OnManualApprovedRequestSelected;
            PromoteManualApprovedButton.OnPressed += _ => PromoteManualApproved();

            _ertSystem.OnStateUpdated += PopulateFromSystem;

            PopulateAutoSpawnTeamList();
            ApplyButtonColors();
            UpdateButtonStates();
            _ertSystem.RequestAdminState();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _ertSystem.OnStateUpdated -= PopulateFromSystem;

            base.Dispose(disposing);
        }

        private void Refresh()
        {
            _ertSystem.RequestAdminState();
        }

        private void OnPendingRequestSelected(ItemList.ItemListSelectedEventArgs args)
        {
            _selectedPendingRequestId = PendingRequestsList[args.ItemIndex].Metadata is int requestId ? requestId : null;
            UpdatePendingDetails();
            UpdateButtonStates();
        }

        private void OnApprovedRequestSelected(ItemList.ItemListSelectedEventArgs args)
        {
            _selectedApprovedRequestId = ApprovedRequestsList[args.ItemIndex].Metadata is int requestId ? requestId : null;
            UpdateApprovedDetails();
            UpdateButtonStates();
        }

        private void OnAutoSpawnTeamSelected(ItemList.ItemListSelectedEventArgs args)
        {
            _selectedAutoSpawnTeamProtoId = AutoSpawnTeamList[args.ItemIndex].Metadata as string;
            UpdateButtonStates();
        }

        private void OnManualApprovedRequestSelected(ItemList.ItemListSelectedEventArgs args)
        {
            _selectedManualApprovedRequestId = ManualApprovedRequestsList[args.ItemIndex].Metadata is int requestId ? requestId : null;
            UpdateManualApprovedDetails();
            UpdateButtonStates();
        }

        private void PopulateFromSystem()
        {
            var state = _ertSystem.LastState;
            if (state == null)
                return;

            PopulatePendingRequestsList(state);
            PopulateApprovedRequestsList(state);
            PopulateManualApprovedRequestsList(state);

            PointsEdit.Text = state.Points.ToString();
            CooldownSeconds.Text = state.CooldownSeconds.ToString();

            UpdatePendingDetails();
            UpdateApprovedDetails();
            UpdateManualApprovedDetails();
            UpdateButtonStates();
        }

        private void PopulateAutoSpawnTeamList()
        {
            var teams = _prototypeManager.EnumeratePrototypes<ErtTeamPrototype>()
                .OrderBy(proto => proto.Name)
                .ToArray();

            AutoSpawnTeamList.Clear();

            foreach (var proto in teams)
            {
                AutoSpawnTeamList.AddItem($"{proto.Name} ({proto.Price})", metadata: proto.ID);
            }

            ReselectByMetadata(AutoSpawnTeamList, _selectedAutoSpawnTeamProtoId);
        }

        private void PopulatePendingRequestsList(ErtAdminStateResponse state)
        {
            PendingRequestsList.Clear();

            foreach (var entry in state.PendingRequests.OrderBy(e => e.RequestId))
            {
                PendingRequestsList.AddItem(
                    $"#{entry.RequestId} {entry.Name} - {entry.SecondsRemaining}s ({entry.Price})",
                    metadata: entry.RequestId);
            }

            ReselectByMetadata(PendingRequestsList, _selectedPendingRequestId);
        }

        private void PopulateApprovedRequestsList(ErtAdminStateResponse state)
        {
            ApprovedRequestsList.Clear();

            foreach (var entry in state.ApprovedRequests.OrderBy(e => e.SecondsRemaining))
            {
                ApprovedRequestsList.AddItem(
                    $"#{entry.RequestId} {entry.Name} - {entry.SecondsRemaining}s ({entry.Price})",
                    metadata: entry.RequestId);
            }

            ReselectByMetadata(ApprovedRequestsList, _selectedApprovedRequestId);
        }

        private void PopulateManualApprovedRequestsList(ErtAdminStateResponse state)
        {
            ManualApprovedRequestsList.Clear();

            foreach (var entry in state.ManualApprovedRequests.OrderBy(e => e.RequestId))
            {
                ManualApprovedRequestsList.AddItem(
                    $"#{entry.RequestId} {entry.Name} ({entry.Price})",
                    metadata: entry.RequestId);
            }

            ReselectByMetadata(ManualApprovedRequestsList, _selectedManualApprovedRequestId);
        }

        private void UpdatePendingDetails()
        {
            var state = _ertSystem.LastState;
            var selected = state?.PendingRequests.FirstOrDefault(x => x.RequestId == _selectedPendingRequestId);

            if (selected == null)
                _selectedPendingRequestId = null;

            PendingRequesterLabel.Text = selected?.RequestedByName ?? string.Empty;
            PendingReasonLabel.SetMessage(selected?.CallReason ?? string.Empty);
        }

        private void UpdateApprovedDetails()
        {
            var state = _ertSystem.LastState;
            var selected = state?.ApprovedRequests.FirstOrDefault(x => x.RequestId == _selectedApprovedRequestId);

            if (selected == null)
            {
                _selectedApprovedRequestId = null;
                ApprovedRequesterLabel.Text = string.Empty;
                ArrivalSeconds.Text = string.Empty;
                return;
            }

            ApprovedRequesterLabel.Text = selected.RequestedByName;
            ArrivalSeconds.Text = selected.SecondsRemaining.ToString();
            ReasonEdit.Text = selected.CallReason ?? string.Empty;
        }

        private void UpdateManualApprovedDetails()
        {
            var state = _ertSystem.LastState;
            var selected = state?.ManualApprovedRequests.FirstOrDefault(x => x.RequestId == _selectedManualApprovedRequestId);

            if (selected == null)
                _selectedManualApprovedRequestId = null;

            ManualApprovedRequesterLabel.Text = selected?.RequestedByName ?? string.Empty;
            ManualApprovedReasonLabel.SetMessage(selected?.CallReason ?? string.Empty);
        }

        private void UpdateButtonStates()
        {
            var hasPendingSelection = _selectedPendingRequestId != null;
            var hasApprovedSelection = _selectedApprovedRequestId != null;
            var hasManualApprovedSelection = _selectedManualApprovedRequestId != null;
            var hasAutoSpawnTeamSelection = !string.IsNullOrEmpty(_selectedAutoSpawnTeamProtoId);

            RejectPendingButton.Disabled = !hasPendingSelection;
            ApprovePendingManualButton.Disabled = !hasPendingSelection;
            ApprovePendingAutoButton.Disabled = !hasPendingSelection;

            SetArrivalButton.Disabled = !hasApprovedSelection;
            SetReasonButton.Disabled = !hasApprovedSelection;
            ChangeApprovedTeamButton.Disabled = !hasApprovedSelection || !hasAutoSpawnTeamSelection;
            QueueAutoSpawnButton.Disabled = !hasAutoSpawnTeamSelection;
            CancelApprovedAutoSpawnButton.Disabled = !hasApprovedSelection;
            MoveApprovedToManualButton.Disabled = !hasApprovedSelection;

            PromoteManualApprovedButton.Disabled = !hasManualApprovedSelection;
        }

        private void RejectPending()
        {
            if (_selectedPendingRequestId == null)
                return;

            _ertSystem.AdminRejectRequest(_selectedPendingRequestId.Value, PendingNotifyCheckBox.Pressed);
            Refresh();
        }

        private void ApprovePendingManual()
        {
            if (_selectedPendingRequestId == null)
                return;

            _ertSystem.AdminApproveRequestManual(_selectedPendingRequestId.Value, PendingNotifyCheckBox.Pressed);
            Refresh();
        }

        private void ApprovePendingAuto()
        {
            if (_selectedPendingRequestId == null)
                return;

            _ertSystem.AdminApproveRequestAuto(_selectedPendingRequestId.Value, PendingNotifyCheckBox.Pressed);
            Refresh();
        }

        private void SetArrival()
        {
            if (_selectedApprovedRequestId == null || !int.TryParse(ArrivalSeconds.Text, out var seconds))
                return;

            _ertSystem.AdminModifyEntry(_selectedApprovedRequestId.Value, seconds);
            Refresh();
        }

        private void SetReason()
        {
            if (_selectedApprovedRequestId == null)
                return;

            _ertSystem.AdminSetReason(_selectedApprovedRequestId.Value, ReasonEdit.Text);
            Refresh();
        }

        private void ChangeApprovedTeam()
        {
            if (_selectedApprovedRequestId == null || string.IsNullOrEmpty(_selectedAutoSpawnTeamProtoId))
                return;

            _ertSystem.AdminSetApprovedTeam(_selectedApprovedRequestId.Value, _selectedAutoSpawnTeamProtoId);
            Refresh();
        }

        private void QueueAutoSpawnRequest()
        {
            if (string.IsNullOrEmpty(_selectedAutoSpawnTeamProtoId))
                return;

            _ertSystem.QueueAutoApprovedRequest(_selectedAutoSpawnTeamProtoId, ReasonEdit.Text);
            Refresh();
        }

        private void CancelApprovedRequest()
        {
            if (_selectedApprovedRequestId == null)
                return;

            _ertSystem.AdminDeleteErt(_selectedApprovedRequestId.Value);
            Refresh();
        }

        private void MoveApprovedToManual()
        {
            if (_selectedApprovedRequestId == null)
                return;

            _ertSystem.AdminMoveApprovedRequestToManual(_selectedApprovedRequestId.Value);
            Refresh();
        }

        private void PromoteManualApproved()
        {
            if (_selectedManualApprovedRequestId == null)
                return;

            _ertSystem.AdminPromoteManualApprovedRequest(_selectedManualApprovedRequestId.Value);
            Refresh();
        }

        private void SetCooldown()
        {
            if (!int.TryParse(CooldownSeconds.Text, out var seconds))
                return;

            _ertSystem.AdminSetCooldown(seconds);
            Refresh();
        }

        private void SetPoints()
        {
            if (!int.TryParse(PointsEdit.Text, out var points))
                return;

            _ertSystem.AdminSetPoints(points);
            Refresh();
        }

        private void ApplyButtonColors()
        {
            RefreshButton.ModulateSelfOverride = Color.FromHex("#1f6feb");
            SetCooldownButton.ModulateSelfOverride = Color.FromHex("#1f6feb");
            SetPointsButton.ModulateSelfOverride = Color.FromHex("#1f6feb");

            RejectPendingButton.ModulateSelfOverride = Color.FromHex("#f85149");
            ApprovePendingManualButton.ModulateSelfOverride = Color.FromHex("#2ea043");
            ApprovePendingAutoButton.ModulateSelfOverride = Color.FromHex("#2ea043");

            SetArrivalButton.ModulateSelfOverride = Color.FromHex("#1f6feb");
            SetReasonButton.ModulateSelfOverride = Color.FromHex("#1f6feb");
            ChangeApprovedTeamButton.ModulateSelfOverride = Color.FromHex("#1f6feb");
            QueueAutoSpawnButton.ModulateSelfOverride = Color.FromHex("#2ea043");
            MoveApprovedToManualButton.ModulateSelfOverride = Color.FromHex("#f0883e");
            CancelApprovedAutoSpawnButton.ModulateSelfOverride = Color.FromHex("#f85149");

            PromoteManualApprovedButton.ModulateSelfOverride = Color.FromHex("#2ea043");
        }

        private static void ReselectByMetadata(ItemList list, object? metadata)
        {
            list.ClearSelected();

            if (metadata == null)
                return;

            for (var i = 0; i < list.Count; i++)
            {
                if (!Equals(list[i].Metadata, metadata))
                    continue;

                list[i].Selected = true;
                break;
            }
        }
    }
}
