// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Client.DeadSpace.Administration.GamePreset;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.GamePreset;

[GenerateTypedNameReferences]
public sealed partial class PresetSettingsWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private GamePresetClientSystem _system = default!;

    public PresetSettingsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _system = _entityManager.System<GamePresetClientSystem>();
        SaveSettingsButton.OnPressed += _ => SaveSettings();

        EnableMaxRdmRowCheckBox.OnToggled += _ => UpdateSpinBoxes();
        EnableMaxRdmDayCheckBox.OnToggled += _ => UpdateSpinBoxes();
    }

    public void LoadSettings(int maxRdmRow, int maxRdmDay, int voteDurationSeconds, bool disableOoc)
    {
        EnableMaxRdmRowCheckBox.Pressed = maxRdmRow > 0;
        MaxRdmRowSpinBox.Value = maxRdmRow > 0 ? maxRdmRow : 2;

        EnableMaxRdmDayCheckBox.Pressed = maxRdmDay > 0;
        MaxRdmDaySpinBox.Value = maxRdmDay > 0 ? maxRdmDay : 5;

        VoteDurationSpinBox.Value = voteDurationSeconds > 0 ? voteDurationSeconds : 30;
        DisableOocCheckBox.Pressed = disableOoc;
        UpdateSpinBoxes();
    }

    private void UpdateSpinBoxes()
    {
        MaxRdmRowSpinBox.ModulateSelfOverride = EnableMaxRdmRowCheckBox.Pressed ? null : Color.FromHex("#666666");
        MaxRdmDaySpinBox.ModulateSelfOverride = EnableMaxRdmDayCheckBox.Pressed ? null : Color.FromHex("#666666");
    }

    private void SaveSettings()
    {
        var maxRow = EnableMaxRdmRowCheckBox.Pressed ? MaxRdmRowSpinBox.Value : 0;
        var maxDay = EnableMaxRdmDayCheckBox.Pressed ? MaxRdmDaySpinBox.Value : 0;
        var voteDuration = VoteDurationSpinBox.Value;
        var disableOoc = DisableOocCheckBox.Pressed;
        _system.UpdatePresetSettings(maxRow, maxDay, voteDuration, disableOoc);
        Close();
    }
}