using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaProgramItem : ContainerButton
{
    public const string StylePropertyBgColor = "backgroundColor";
    // DS14-start
    public const string NormalBgColor = "#121821F0";
    public const string HoverColor = "#17283AF4";
    public const string PressedColor = "#1B3448F5";
    // DS14-end

    private readonly StyleBoxFlat _styleBox = new()
    {
        // DS14-start
        BackgroundColor = Color.FromHex(NormalBgColor),
        BorderColor = Color.FromHex("#2D4757"),
        BorderThickness = new Thickness(1),
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
        ContentMarginLeftOverride = 6,
        ContentMarginRightOverride = 6,
        // DS14-end
    };

    public Color BackgroundColor
    {
        get => _styleBox.BackgroundColor;
        set => _styleBox.BackgroundColor = value;
    }

    public PdaProgramItem()
    {
        RobustXamlLoader.Load(this);
        Panel.PanelOverride = _styleBox;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (TryGetStyleProperty<Color>(StylePropertyBgColor, out var bgColor))
            BackgroundColor = bgColor;

    }
}
