using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaSettingsButton : ContainerButton
{
    public const string StylePropertyFgColor = "foregroundColor";
    public const string StylePropertyBgColor = "backgroundColor";
    // DS14-start
    public const string NormalBgColor = "#111923F0";
    public const string HoverColor = "#162638F4";
    public const string PressedColor = "#18344AF5";
    public const string DisabledFgColor = "#7A8590";
    public const string EnabledFgColor = "#F1F3F6";
    // DS14-end

    private readonly StyleBoxFlat _styleBox = new()
    {
        // DS14-start
        BackgroundColor = Color.FromHex(NormalBgColor),
        BorderColor = Color.FromHex("#2D4757"),
        BorderThickness = new Thickness(1),
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
        ContentMarginLeftOverride = 9,
        ContentMarginRightOverride = 9,
        // DS14-end
    };

    public string? Text
    {
        get => OptionName.Text;
        set => OptionName.Text = value;
    }
    public string? Description
    {
        get => OptionDescription.Text;
        set => OptionDescription.Text = value;
    }

    public Color BackgroundColor
    {
        get => _styleBox.BackgroundColor;
        set => _styleBox.BackgroundColor = value;
    }

    public Color? ForegroundColor
    {
        get => OptionName.FontColorOverride;

        set
        {
            OptionName.FontColorOverride = value;
            OptionDescription.FontColorOverride = value;
        }
    }

    public PdaSettingsButton()
    {
        RobustXamlLoader.Load(this);
        Panel.PanelOverride = _styleBox;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (TryGetStyleProperty<Color>(StylePropertyBgColor, out var bgColor))
            BackgroundColor = bgColor;

        if (TryGetStyleProperty<Color>(StylePropertyFgColor, out var fgColor))
            ForegroundColor = fgColor;

    }
}
