using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class StampCollection : Container
{
    // DS14-start
    private const int MaxColumns = 3;
    private const float ColumnGap = 6.0f;
    private const float RowGap = 6.0f;
    private const float FallbackStampZoneWidth = 520.0f;

    private readonly List<StampWidget> _stamps = new();
    private readonly List<List<int>> _rows = new();
    // DS14-end

    public StampCollection()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Remove any stamps from the page.
    /// </summary>
    public void RemoveStamps()
    {
        // DS14-start
        RemoveAllChildren();
        _rows.Clear();
        InvalidateMeasure();
        // DS14-end

        _stamps.Clear();
        InvalidateArrange();
    }

    /// <summary>
    /// Adds a stamp to the display; will perform automatic layout.
    /// </summary>
    public void AddStamp(StampWidget s)
    {
        _stamps.Add(s);
        AddChild(s);

        // DS14-start
        InvalidateMeasure();
        InvalidateArrange();
    }

    protected override Vector2 MeasureOverride(Vector2 availableSize)
    {
        var availablePixelWidth = GetAvailablePixelWidth(availableSize.X);
        var scale = MathF.Max(UIScale, 0.001f);
        var cappedAvailableSize = new Vector2(availablePixelWidth / scale, availableSize.Y);

        foreach (var stamp in _stamps)
        {
            stamp.Measure(cappedAvailableSize);
        }

        BuildRows(availablePixelWidth);

        var desiredPixelHeight = GetRowsPixelHeight();

        return new Vector2(availablePixelWidth / scale, desiredPixelHeight / scale);
    }
    // DS14-end

    protected override Vector2 ArrangeOverride(Vector2 finalSize)
    {
        // DS14-start
        var controlBox = new UIBox2(Vector2.Zero, finalSize * UIScale);
        var availableWidth = MathF.Max(0.0f, controlBox.Width);
        BuildRows(availableWidth);

        var y = controlBox.Top;
        foreach (var rowIndices in _rows)
        {
            var rowHeight = 0.0f;
            foreach (var index in rowIndices)
            {
                rowHeight = MathF.Max(rowHeight, _stamps[index].DesiredPixelSize.Y);
            }

            var x = controlBox.Left;
            foreach (var index in rowIndices)
            {
                var finalPosition = new Vector2(
                    x,
                    y + MathF.Max(0.0f, (rowHeight - _stamps[index].DesiredPixelSize.Y) * 0.5f));
                var finalPositionAsInt = new Vector2i((int) MathF.Round(finalPosition.X), (int) MathF.Round(finalPosition.Y));
                _stamps[index].ArrangePixel(new UIBox2i(finalPositionAsInt, finalPositionAsInt + _stamps[index].DesiredPixelSize));

                x += _stamps[index].DesiredPixelSize.X + ColumnGap;
            }

            y += rowHeight + RowGap;
        }
        // DS14-end

        return finalSize;
    }

    // DS14-start
    private float GetAvailablePixelWidth(float availableWidth)
    {
        var scale = MathF.Max(UIScale, 0.001f);

        if (float.IsNaN(availableWidth) || float.IsInfinity(availableWidth) || availableWidth <= 0.0f)
            return FallbackStampZoneWidth * scale;

        return availableWidth * scale;
    }

    private float GetRowsPixelHeight()
    {
        var height = 0.0f;

        for (var row = 0; row < _rows.Count; row++)
        {
            var rowHeight = 0.0f;
            foreach (var index in _rows[row])
            {
                rowHeight = MathF.Max(rowHeight, _stamps[index].DesiredPixelSize.Y);
            }

            height += rowHeight;

            if (row < _rows.Count - 1)
                height += RowGap;
        }

        return height;
    }

    private void BuildRows(float availableWidth)
    {
        _rows.Clear();

        for (var i = 0; i < _stamps.Count; i++)
        {
            if (_rows.Count == 0 || !CanFit(_rows[^1], i, availableWidth))
                _rows.Add(new List<int>());

            _rows[^1].Add(i);
        }
    }

    private bool CanFit(List<int> row, int stampIndex, float availableWidth)
    {
        if (row.Count >= MaxColumns)
            return false;

        var width = (float) _stamps[stampIndex].DesiredPixelSize.X;
        foreach (var index in row)
        {
            width += _stamps[index].DesiredPixelSize.X + ColumnGap;
        }

        return width <= availableWidth;
    }
    // DS14-end
}
