// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT
using System.Collections.Generic;
using System.Linq;
using Content.Shared.DeadSpace._Soyuz.Roadmap;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace._Soyuz.Roadmap;

[GenerateTypedNameReferences]
public sealed partial class RoadmapWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public RoadmapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        
        LoadRoadmapData();
    }

    private void LoadRoadmapData()
    {
        var completed = new List<RoadmapEntryData>();
        var inProgress = new List<RoadmapEntryData>();
        var planned = new List<RoadmapEntryData>();

        foreach (var proto in _prototypeManager.EnumeratePrototypes<RoadmapEntryPrototype>())
        {
            var entry = new RoadmapEntryData
            {
                Id = proto.ID,
                Title = proto.Title,
                Description = proto.Description,
                Order = proto.Order,
                Tags = new List<string>(proto.Tags)
            };

            switch (proto.Category)
            {
                case RoadmapCategory.Completed:
                    completed.Add(entry);
                    break;
                case RoadmapCategory.InProgress:
                    inProgress.Add(entry);
                    break;
                case RoadmapCategory.Planned:
                    planned.Add(entry);
                    break;
            }
        }

        UpdateRoadmap(completed, inProgress, planned);
    }

    public void UpdateRoadmap(List<RoadmapEntryData> completed, List<RoadmapEntryData> inProgress, List<RoadmapEntryData> planned)
    {
        CompletedContainer.RemoveAllChildren();
        InProgressContainer.RemoveAllChildren();
        PlannedContainer.RemoveAllChildren();
        
        AddEntries(CompletedContainer, completed.OrderBy(x => x.Order).ToList());
        AddEntries(InProgressContainer, inProgress.OrderBy(x => x.Order).ToList());
        AddEntries(PlannedContainer, planned.OrderBy(x => x.Order).ToList());
    }

    private void AddEntries(BoxContainer container, List<RoadmapEntryData> entries)
    {
        if (entries == null || !entries.Any())
        {
            var emptyLabel = new Label 
            { 
                Text = "Пока ничего нет",
                FontColorOverride = Color.Gray,
                Margin = new Thickness(8),
                HorizontalAlignment = HAlignment.Center
            };
            container.AddChild(emptyLabel);
            return;
        }

        foreach (var entry in entries)
        {
            container.AddChild(CreateEntryCard(entry));
        }
    }

    private Control CreateEntryCard(RoadmapEntryData entry)
    {
        var card = new PanelContainer
        {
            Margin = new Thickness(0, 0, 0, 8),
            HorizontalExpand = true
        };

        var cardStyle = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#2a2a3e"),
            ContentMarginLeftOverride = 10,
            ContentMarginRightOverride = 10,
            ContentMarginTopOverride = 8,
            ContentMarginBottomOverride = 8
        };
        card.PanelOverride = cardStyle;

        var mainBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            MaxWidth = 350
        };

        var headerBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };

        var toggleButton = new Button
        {
            Text = "↓",
            MinWidth = 30,
            MaxWidth = 30
        };

        var titleLabel = new Label
        {
            Text = entry.Title,
            StyleClasses = { "LabelHeading" },
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(5, 0, 0, 0),
            ClipText = true
        };

        headerBox.AddChild(toggleButton);
        headerBox.AddChild(titleLabel);
        mainBox.AddChild(headerBox);

        var shortDesc = GetShortDescription(entry.Description);
        Label? shortDescLabel = null;
        if (!string.IsNullOrEmpty(shortDesc))
        {
            shortDescLabel = new Label
            {
                Text = shortDesc,
                FontColorOverride = Color.FromHex("#cccccc"),
                Margin = new Thickness(35, 5, 0, 0),
                HorizontalExpand = true,
                ClipText = true
            };
            mainBox.AddChild(shortDescLabel);
        }

        BoxContainer? tagsTopContainer = null;
        if (entry.Tags != null && entry.Tags.Any())
        {
            tagsTopContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(35, 5, 0, 0),
                HorizontalExpand = true
            };

            foreach (var tag in entry.Tags)
            {
                var tagPanel = new PanelContainer
                {
                    Margin = new Thickness(0, 0, 6, 0)
                };

                var tagStyle = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#222246"),
                    ContentMarginLeftOverride = 6,
                    ContentMarginRightOverride = 6,
                    ContentMarginTopOverride = 2,
                    ContentMarginBottomOverride = 2
                };
                tagPanel.PanelOverride = tagStyle;

                var tagLabel = new Label
                {
                    Text = tag,
                    FontColorOverride = Color.FromHex("#aaaaaa")
                };

                tagPanel.AddChild(tagLabel);
                tagsTopContainer.AddChild(tagPanel);
            }

            mainBox.AddChild(tagsTopContainer);
        }


        var collapsibleContent = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Visible = false
        };

        if (!string.IsNullOrEmpty(entry.Description))
        {
            var descLabel = new RichTextLabel
            {
                Margin = new Thickness(35, 5, 0, 5),
                MaxWidth = 280,
                HorizontalExpand = true
            };
            descLabel.SetMessage(entry.Description);
            collapsibleContent.AddChild(descLabel);
        }

        BoxContainer? tagsBottomContainer = null;
        if (entry.Tags != null && entry.Tags.Any())
        {
            tagsBottomContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(35, 0, 0, 5),
                HorizontalExpand = true
            };

            foreach (var tag in entry.Tags)
            {
                var tagPanel = new PanelContainer
                {
                    Margin = new Thickness(0, 0, 6, 0)
                };

                var tagStyle = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#3a3a5e"),
                    ContentMarginLeftOverride = 6,
                    ContentMarginRightOverride = 6,
                    ContentMarginTopOverride = 2,
                    ContentMarginBottomOverride = 2
                };
                tagPanel.PanelOverride = tagStyle;

                var tagLabel = new Label
                {
                    Text = tag,
                    FontColorOverride = Color.FromHex("#aaaaaa")
                };

                tagPanel.AddChild(tagLabel);
                tagsBottomContainer.AddChild(tagPanel);
            }

            collapsibleContent.AddChild(tagsBottomContainer);
        }

        mainBox.AddChild(collapsibleContent);

        var hasDescription = !string.IsNullOrEmpty(entry.Description);
        var hasTags = entry.Tags != null && entry.Tags.Any();
        
        toggleButton.OnPressed += _ =>
        {
            var isExpanded = !collapsibleContent.Visible;
            collapsibleContent.Visible = isExpanded;
            toggleButton.Text = isExpanded ? "↑" : "↓";
            
            if (shortDescLabel != null)
            {
                shortDescLabel.Visible = !isExpanded;
            }
            
            if (tagsTopContainer != null)
            {
                tagsTopContainer.Visible = !isExpanded;
            }
        };

        if (!hasDescription && !hasTags)
        {
            toggleButton.Visible = false;
        }
        else if (!hasDescription && hasTags)
        {
            toggleButton.Visible = false;
            tagsBottomContainer!.Visible = false;
        }

        card.AddChild(mainBox);
        return card;
    }

    private string GetShortDescription(string? fullDescription)
    {
        if (string.IsNullOrEmpty(fullDescription))
            return string.Empty;

        var firstLine = fullDescription.Split('\n')[0].Trim();
        
        if (firstLine.Length <= 30)
            return firstLine;

        return firstLine.Substring(0, 30) + "...";
    }
}
