## Static recipes

- type: latheRecipePack
  id: SecurityEquipmentStatic
  recipes:
  - ClothingEyesHudSecurity
  - ForensicPad
  - Handcuffs
  - TargetClown
  - TargetHuman
  - TargetSyndicate
  - Zipties

# Practice ammo/mags and practice weapons
- type: latheRecipePack
  id: SecurityPracticeStatic
  recipes:
  - BoxShotgunPractice
  - MagazineBoxLightRiflePractice
  - MagazineBoxMagnumPractice
  - MagazineBoxPistolPractice
  - MagazineBoxRiflePractice
  - WeaponDisablerPractice
  - WeaponLaserCarbinePractice
  - MagazineLightRiflePractice
  - MagazineRiflePractice
  - MagazinePistolPractice
  - SpeedLoaderMagnumPractice
  - MagazinePistolSubMachineGunPractice
  - WeaponFlareGunSecurity

# Shared between secfab and emagged autolathe
- type: latheRecipePack
  id: SecurityAmmoStatic
  recipes:
  - BoxLethalshot
  - BoxShotgunSlug
  - MagazineShotgun # DS14
  - MagazineShotgunSlug # DS14
  - MagazineShotgunEmpty # DS14
  - MagazineBoxLightRifle
  - MagazineBoxMagnum
  - MagazineBoxPistol
  - MagazineBoxRifle
  - MagazineLightRifle
  - MagazineLightRifleEmpty
  - MagazinePistol
  - MagazinePistolMTS #DS14-Soyuz
  - MagazinePistolEmpty
  - MagazinePistolSubMachineGun
  - MagazinePistolSubMachineGunEmpty
  - MagazinePistolSubMachineGunTopMounted
  - MagazinePistolSubMachineGunTopMountedEmpty
  - MagazineRifle
  - MagazineRifleEmpty
  - SpeedLoaderMagnum
  - SpeedLoaderMagnumEmpty

- type: latheRecipePack
  id: SecurityWeaponsStatic
  recipes:
  - Flash
  - Stunbaton
  - CombatKnife
  - RiotShield

# DS14-start
- type: latheRecipePack
  id: SecurityBorgModulesStatic
  recipes:
  - BorgModuleArrestSecurity
  - BorgModulEnergySecurity
# DS14-end

## Dynamic recipes

- type: latheRecipePack
  id: SecurityEquipment
  recipes:
  - ClothingBackpackElectropack
  - HoloprojectorSecurity
  - PortableRecharger
  - PowerCageHigh
  - PowerCageMedium
  - PowerCageSmall
  - TelescopicShield
  - ClothingBackpackHarmpack

# DS14-start
- type: latheRecipePack
  id: NightVisionTech
  recipes:
  - ClothingEyesPNV
# DS14-end

- type: latheRecipePack
  id: SecurityBoards
  recipes:
  - ShuttleGunDusterCircuitboard
  - ShuttleGunFriendshipCircuitboard
  - ShuttleGunPerforatorCircuitboard
  - ShuttleGunSvalinnMachineGunCircuitboard
  - WeaponEnergyTurretCommandMachineCircuitboard # DS14
  - WeaponEnergyTurretCommandControlPanelElectronics # DS14

- type: latheRecipePack
  parent:
  - ScienceExplosives # sec gets everything for modular grenade making that sci does
  id: SecurityExplosives
  recipes:
  - CableDetStack1
  - EmptyDetonator
  - ExplosivePayload
  - GrenadeBlast
  - GrenadeEMP
  - GrenadeFlash
  - MagazineGrenadeEmpty

# Shared between secfab and emagged protolathe
- type: latheRecipePack
  id: SecurityAmmo
  recipes:
  - BoxBeanbag
  - BoxShotgunIncendiary
  - BoxShotgunUranium
  - BoxShellTranquilizer
  - MagazineBoxLightRifleIncendiary
  - MagazineBoxLightRifleUranium
  - MagazineBoxMagnumIncendiary
  - MagazineBoxMagnumUranium
  - MagazineBoxPistolIncendiary
  - MagazineBoxPistolUranium
  - MagazineBoxRifleIncendiary
  - MagazineBoxRifleUranium
  - MagazineLightRifleIncendiary
  - MagazineLightRifleUranium
  - MagazinePistolIncendiary
  - MagazinePistolUranium
  - MagazinePistolSubMachineGunIncendiary
  - MagazinePistolSubMachineGunUranium
  - MagazineRifleIncendiary
  - MagazineRifleUranium
  - MagazineShotgunBeanbag
  - MagazineShotgunIncendiary
  - SpeedLoaderMagnumIncendiary
  - SpeedLoaderMagnumUranium
  - MagazineBox357Incendiary # ADT
  - MagazinePistolHighCapacity #DS14
  - ADTMagazineShotgunXL # DS14
  - BoxLethalshotMagnum # DS14
  - ADTExtMagazineRifle # DS14
#DS14-soyuz-start
  - MagazineBox357Silver
  - MagazineBoxLightestRifleSilver
  - MagazineBoxRifleSilver
  - MagazineBoxLightRifleSilver
  - MagazineBoxPistolSilver
  - BoxLethalshotSilver
  - MagazinePistolSilver
  - MagazineLightRifleSilver
  - MagazineRifleSilver
  - MagazineShotgunSilver
  - SpeedLoaderMagnumSilver
  - MagazinePistolSubMachineGunSilver
#DS14-soyuz-end

- type: latheRecipePack
  id: SecurityWeapons
  recipes:
  - Truncheon
  - WeaponAdvancedLaser
  - WeaponLaserCannon
  - WeaponLaserCarbine
  - WeaponXrayCannon
  - WeaponTemperatureGun
  - WeaponLaserRifle # DS14
  - WeaponIonRifle # DS14
  - PhotonShotgun # DS14
  - CartridgeLaserRifle # DS14
  - EnergyCartridge # DS14

- type: latheRecipePack
  id: SecurityDisablers
  recipes:
  - WeaponDisabler
  - WeaponDisablerSMG

# DS14-Soyuz-start
- type: latheRecipePack
  id: SecurityPoliceBeta
  recipes:
  - PoliceBetaLegs
  - PoliceBetaHead
  - PoliceBetaComp
  - PoliceBetaBody
# DS14-Soyuz-end
